# Generated by Django 2.1.2 on 2018-10-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsrite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='website_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
